export type Type =
  | 'Event'
  | 'Task'
  | 'Group'
  | 'Relation'
  | 'NDay'
  | 'Link'
  | 'VirtualLocation'
  | 'Location'
  | 'Alert'
  | 'RecurrenceRule'
  | 'Participant'
  | 'OffsetTrigger'
  | 'AbsoluteTrigger'
  | 'UnknownTrigger'
  | 'TimeZone'
  | 'TimeZoneRule';
